apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: payment-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: payment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: payment-service
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: payment
  name: payment
spec:
  finalizers:
    - kubernetes
