apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: staging
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: products-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  namespace: staging
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: products-service
          ports:
            - containerPort: 80
