apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: production
  name: production
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: staging
  name: staging
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: qa
  name: qa
spec:
  finalizers:
    - kubernetes
---

